engines:
  eslint:
    enabled: true
    channel: "eslint-2"
    checks:
      import/no-unresolved:
        enabled: false
ratings:
  paths:
  - app/**
  - spec/**
exclude_paths:
- coverage/**/*
- node_modules/**/*
