---
engines:
  eslint:
    enabled: true
    channel: eslint-2
    checks:
      import/no-unresolved:
        enabled: false
  duplication:
    enabled: true
    exclude_fingerprints:
    - e6dcc31607f95950f35c4630807c773f
    - 9968e65cb8ff3f6ac453f3413613e960
    - ceb27f17228ec68df33676a736ee8045
    - e9770c9be6905b9dba54944eca6cc967
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
ratings:
  paths:
  - app/**
  - spec/**
exclude_paths:
- coverage/**/*
- node_modules/**/*
